#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("MasterDetail.Droid.Resource", IsApplication=true)]

namespace MasterDetail.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Reactive.Bindings.Resource.String.ApplicationName = global::MasterDetail.Droid.Resource.String.ApplicationName;
			global::Reactive.Bindings.Resource.String.Hello = global::MasterDetail.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int button = 2131034112;
			
			// aapt resource value: 0x7f05000c
			public const int button_add = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int edittext_description = 2131034123;
			
			// aapt resource value: 0x7f050009
			public const int edittext_title = 2131034121;
			
			// aapt resource value: 0x7f050001
			public const int listView = 2131034113;
			
			// aapt resource value: 0x7f050008
			public const int myButton = 2131034120;
			
			// aapt resource value: 0x7f050002
			public const int textView1 = 2131034114;
			
			// aapt resource value: 0x7f05000a
			public const int textView2 = 2131034122;
			
			// aapt resource value: 0x7f050004
			public const int textView3 = 2131034116;
			
			// aapt resource value: 0x7f050007
			public const int text_description = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int text_title = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int textview_description = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int textview_title = 2131034115;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Browse = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Detail = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ListItem_Browse = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int NewItem = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int app_name = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int hello = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
